### ISSUE TITLE
Missing README.md File 

### ISSUE THREAD

**Issue by Elouaeramine** [sofiene-chihi/paho-mqtt-communication#1]
I couldn't help but notice there is no README.md file.
How am I supposed to understand how the project works.

**Comment by sofiene-chihi** [comment]
Yes, I'm aware of that point. I was in a rush when pushing the source code just to help some fellows understand the IoT course.
I'm just gonna add a small explanation of the scope and what is the code doing and I'll provide more details soon :wink: .
